samples:
  SRR24300527_92: SRR24300527.combined.fastq.merged.sort.sam.gz
  SRR24300528_92: SRR24300528.combined.fastq.merged.sort.sam.gz
metaDMG_cpp: /projects/lundbeck/people/npl206/programmes/metaDMG-cpp/metaDMG-cpp
names: /projects/wintherpedersen/data/ncbi_taxonomy_01Oct2022/names.dmp
nodes: /projects/wintherpedersen/data/ncbi_taxonomy_01Oct2022/nodes.dmp
acc2tax: /projects/wintherpedersen/data/ncbi_taxonomy_01Oct2022/combined_accession2taxid_20221112.gz
min_similarity_score: 0.92
max_similarity_score: 1.0
min_mapping_quality: 0
lca_rank: ''
max_position: 30
min_reads: 0
weight_type: 1
custom_database: false
forward_only: false
stopIfErrors: 0
output_dir: data_95sim
parallel_samples: 2
cores_per_sample: 8
bayesian: false
config_file: config.yaml
damage_mode: lca
version: 0.38.0
