samples:
  SRR24300527: /path/to/mapping/SRR24300527.filtered.bam
  SRR24300528: /path/to/mapping/SRR24300528.filtered.bam

metaDMG_cpp: /path/to/apps/bin/metaDMG-cpp
names: /path/to/db/Vanilla/names.dmp
nodes: /path/to/db/Vanilla/nodes.dmp
acc2tax: /path/to/db/Vanilla/acc2tax.map.gz
min_similarity_score: 0.95
max_similarity_score: 1.0
min_mapping_quality: 0
lca_rank: ''
max_position: 35
min_reads: 0
weight_type: 1
custom_database: true
forward_only: false
output_dir: mapping/metadmg/
parallel_samples: 1
cores_per_sample: 5
bayesian: true
config_file: metadmg_pr_config.yaml
damage_mode: local
version: 0.38.0
